export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        
        <div className="prose prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Service Description</h2>
            <p className="text-muted-foreground">
              SilverTrade AI is an algorithmic signal generation tool that provides technical analysis-based trading signals. 
              SilverTrade AI is NOT an investment advisor and does NOT provide investment advice. 
              All signals are generated by automated algorithms based on technical indicators and historical data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. User Eligibility</h2>
            <p className="text-muted-foreground">
              You must be at least 18 years old and legally permitted to trade in your jurisdiction to use this service. 
              By using SilverTrade AI, you represent and warrant that you meet these requirements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Risk Acknowledgment</h2>
            <p className="text-muted-foreground">
              Trading involves substantial risk of loss, including the loss of your entire investment. 
              Past performance of signals is not indicative of future results. 
              You acknowledge that all trading decisions and risks are solely your responsibility.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. No Guarantee of Returns</h2>
            <p className="text-muted-foreground">
              SilverTrade AI does NOT guarantee any returns or profits. 
              Signal accuracy is based on historical backtesting and does not guarantee future performance. 
              You may lose money trading based on these signals.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Data Usage</h2>
            <p className="text-muted-foreground">
              We collect and process your email, usage data, trading activity, and IP address as described in our Privacy Policy. 
              Your broker credentials are stored encrypted and are never shared with third parties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Subscription Terms</h2>
            <p className="text-muted-foreground">
              Subscription fees are for software/platform access, NOT for investment advice or signals. 
              You may cancel your subscription at any time through your account settings. 
              Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              SilverTrade AI is not liable for any trading losses you may incur. 
              Our maximum liability is limited to the amount you paid for your subscription in the preceding 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Governing Law</h2>
            <p className="text-muted-foreground">
              These terms are governed by Indian law. Any disputes shall be resolved through arbitration in India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. SEBI Disclaimer</h2>
            <p className="text-muted-foreground">
              <strong>IMPORTANT:</strong> SilverTrade AI is NOT registered as a SEBI Investment Advisor or Research Analyst. 
              Signals provided are algorithmic outputs of a technical analysis system and do NOT constitute research reports 
              or investment recommendations as defined under SEBI regulations.
            </p>
          </section>

          <section className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-lg">
            <p className="text-sm text-amber-600 dark:text-amber-400">
              <strong>By using SilverTrade AI, you acknowledge that:</strong>
              <br />• This is an algorithmic tool, not financial advice
              <br />• All trading risk is yours alone
              <br />• Past performance does not guarantee future results
              <br />• SilverTrade AI is not a SEBI-registered investment advisor
            </p>
          </section>
        </div>

        <p className="text-sm text-muted-foreground mt-8">
          Last updated: {new Date().toLocaleDateString()}
        </p>
      </div>
    </div>
  )
}
